/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Deity {
  'id' : bigint,
  'name' : MultilingualText,
  'description' : MultilingualText,
  'iconEmoji' : string,
}
export interface Mantra {
  'id' : bigint,
  'sanskritText' : string,
  'meaning' : MultilingualText,
  'name' : MultilingualText,
  'deityId' : bigint,
  'audioUrl' : string,
  'transliteration' : string,
  'category' : string,
  'benefits' : MultilingualText,
}
export interface MultilingualText {
  'hindi' : string,
  'telugu' : string,
  'english' : string,
}
export interface Stotra {
  'id' : bigint,
  'title' : MultilingualText,
  'verses' : Array<Verse>,
  'category' : string,
}
export interface UserPreferences {
  'bookmarkedItems' : Array<string>,
  'language' : string,
}
export interface Verse {
  'sanskritText' : string,
  'meaning' : MultilingualText,
  'transliteration' : string,
  'number' : bigint,
}
export interface _SERVICE {
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'getAllDeities' : ActorMethod<[], Array<Deity>>,
  'getAllMantras' : ActorMethod<[], Array<Mantra>>,
  'getAllStotras' : ActorMethod<[], Array<Stotra>>,
  'getDailySuggestion' : ActorMethod<[], bigint>,
  'getMantraById' : ActorMethod<[bigint], [] | [Mantra]>,
  'getMantrasByDeity' : ActorMethod<[bigint], Array<Mantra>>,
  'getPreferences' : ActorMethod<[], UserPreferences>,
  'getStotraById' : ActorMethod<[bigint], [] | [Stotra]>,
  'getUserFavorites' : ActorMethod<[], Array<bigint>>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'searchMantras' : ActorMethod<[string], Array<Mantra>>,
  'setPreferences' : ActorMethod<[string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];