/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MultilingualText = IDL.Record({
  'hindi' : IDL.Text,
  'telugu' : IDL.Text,
  'english' : IDL.Text,
});
export const Deity = IDL.Record({
  'id' : IDL.Nat,
  'name' : MultilingualText,
  'description' : MultilingualText,
  'iconEmoji' : IDL.Text,
});
export const Mantra = IDL.Record({
  'id' : IDL.Nat,
  'sanskritText' : IDL.Text,
  'meaning' : MultilingualText,
  'name' : MultilingualText,
  'deityId' : IDL.Nat,
  'audioUrl' : IDL.Text,
  'transliteration' : IDL.Text,
  'category' : IDL.Text,
  'benefits' : MultilingualText,
});
export const Verse = IDL.Record({
  'sanskritText' : IDL.Text,
  'meaning' : MultilingualText,
  'transliteration' : IDL.Text,
  'number' : IDL.Nat,
});
export const Stotra = IDL.Record({
  'id' : IDL.Nat,
  'title' : MultilingualText,
  'verses' : IDL.Vec(Verse),
  'category' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'bookmarkedItems' : IDL.Vec(IDL.Text),
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'getAllDeities' : IDL.Func([], [IDL.Vec(Deity)], ['query']),
  'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
  'getAllStotras' : IDL.Func([], [IDL.Vec(Stotra)], ['query']),
  'getDailySuggestion' : IDL.Func([], [IDL.Nat], ['query']),
  'getMantraById' : IDL.Func([IDL.Nat], [IDL.Opt(Mantra)], ['query']),
  'getMantrasByDeity' : IDL.Func([IDL.Nat], [IDL.Vec(Mantra)], ['query']),
  'getPreferences' : IDL.Func([], [UserPreferences], []),
  'getStotraById' : IDL.Func([IDL.Nat], [IDL.Opt(Stotra)], ['query']),
  'getUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'searchMantras' : IDL.Func([IDL.Text], [IDL.Vec(Mantra)], ['query']),
  'setPreferences' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MultilingualText = IDL.Record({
    'hindi' : IDL.Text,
    'telugu' : IDL.Text,
    'english' : IDL.Text,
  });
  const Deity = IDL.Record({
    'id' : IDL.Nat,
    'name' : MultilingualText,
    'description' : MultilingualText,
    'iconEmoji' : IDL.Text,
  });
  const Mantra = IDL.Record({
    'id' : IDL.Nat,
    'sanskritText' : IDL.Text,
    'meaning' : MultilingualText,
    'name' : MultilingualText,
    'deityId' : IDL.Nat,
    'audioUrl' : IDL.Text,
    'transliteration' : IDL.Text,
    'category' : IDL.Text,
    'benefits' : MultilingualText,
  });
  const Verse = IDL.Record({
    'sanskritText' : IDL.Text,
    'meaning' : MultilingualText,
    'transliteration' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Stotra = IDL.Record({
    'id' : IDL.Nat,
    'title' : MultilingualText,
    'verses' : IDL.Vec(Verse),
    'category' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'bookmarkedItems' : IDL.Vec(IDL.Text),
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'getAllDeities' : IDL.Func([], [IDL.Vec(Deity)], ['query']),
    'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
    'getAllStotras' : IDL.Func([], [IDL.Vec(Stotra)], ['query']),
    'getDailySuggestion' : IDL.Func([], [IDL.Nat], ['query']),
    'getMantraById' : IDL.Func([IDL.Nat], [IDL.Opt(Mantra)], ['query']),
    'getMantrasByDeity' : IDL.Func([IDL.Nat], [IDL.Vec(Mantra)], ['query']),
    'getPreferences' : IDL.Func([], [UserPreferences], []),
    'getStotraById' : IDL.Func([IDL.Nat], [IDL.Opt(Stotra)], ['query']),
    'getUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'searchMantras' : IDL.Func([IDL.Text], [IDL.Vec(Mantra)], ['query']),
    'setPreferences' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };