/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Verse {
    sanskritText: string;
    meaning: MultilingualText;
    transliteration: string;
    number: bigint;
}
export interface Mantra {
    id: bigint;
    sanskritText: string;
    meaning: MultilingualText;
    name: MultilingualText;
    deityId: bigint;
    audioUrl: string;
    transliteration: string;
    category: string;
    benefits: MultilingualText;
}
export interface UserPreferences {
    bookmarkedItems: Array<string>;
    language: string;
}
export interface Stotra {
    id: bigint;
    title: MultilingualText;
    verses: Array<Verse>;
    category: string;
}
export interface Deity {
    id: bigint;
    name: MultilingualText;
    description: MultilingualText;
    iconEmoji: string;
}
export interface MultilingualText {
    hindi: string;
    telugu: string;
    english: string;
}
export interface backendInterface {
    addFavorite(itemId: bigint): Promise<void>;
    getAllDeities(): Promise<Array<Deity>>;
    getAllMantras(): Promise<Array<Mantra>>;
    getAllStotras(): Promise<Array<Stotra>>;
    getDailySuggestion(): Promise<bigint>;
    getMantraById(id: bigint): Promise<Mantra | null>;
    getMantrasByDeity(deityId: bigint): Promise<Array<Mantra>>;
    getPreferences(): Promise<UserPreferences>;
    getStotraById(id: bigint): Promise<Stotra | null>;
    getUserFavorites(): Promise<Array<bigint>>;
    removeFavorite(itemId: bigint): Promise<void>;
    searchMantras(keyword: string): Promise<Array<Mantra>>;
    setPreferences(language: string, bookmarkedItems: Array<string>): Promise<void>;
}
import type { Mantra as _Mantra, Stotra as _Stotra } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async getAllDeities(): Promise<Array<Deity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeities();
            return result;
        }
    }
    async getAllMantras(): Promise<Array<Mantra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMantras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMantras();
            return result;
        }
    }
    async getAllStotras(): Promise<Array<Stotra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStotras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStotras();
            return result;
        }
    }
    async getDailySuggestion(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySuggestion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySuggestion();
            return result;
        }
    }
    async getMantraById(arg0: bigint): Promise<Mantra | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMantraById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMantraById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMantrasByDeity(arg0: bigint): Promise<Array<Mantra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMantrasByDeity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMantrasByDeity(arg0);
            return result;
        }
    }
    async getPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return result;
        }
    }
    async getStotraById(arg0: bigint): Promise<Stotra | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStotraById(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStotraById(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFavorites(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFavorites();
            return result;
        }
    }
    async removeFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async searchMantras(arg0: string): Promise<Array<Mantra>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMantras(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMantras(arg0);
            return result;
        }
    }
    async setPreferences(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPreferences(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPreferences(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mantra]): Mantra | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stotra]): Stotra | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
